name: wakatime-charts

on:
  schedule:
    # Runs Hourly
    - cron: "0 * * * *"
  # To Run It Manualy
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme Charts
    runs-on: ubuntu-20.04
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
          SHOW_LOC_CHART: "True"
